# -*- coding: utf-8 -*-
"""ExamenParcial1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HZA-NUiLnN3oQFeo7nO9Ozl7C_3ZrfA4
"""

def es_primo(numero):
  if numero <= 1:
    return False
  if numero <= 3:
    return True
  if numero % 2==0 or numero % 3==0:
    return False

  i=5
  while i*i < numero:
    if numero % i==0 or numero % (i+2)==0:

      return False
    i+=6
  return True

def nextPrimo (n):
  if n<2: return False
  i = n
  while True:
    i += 1
    if es_primo(i): return i


def median(a,b,c):
    dato=[a,b,c]
    dato.sort()
    return dato[1]

import random

def gen_password():
  password = ""
  for i in range(1,random.randrange(7,10,1)):
    password += chr(random.randrange(33,126,1))
  return password

def hip(a,b):
  resultado = (a*a) + (b*b)
  return resultado**.5
